/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.wanhive.basic.arithexp;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTADD = 1;
  public int JJTMULT = 2;
  public int JJTFACTOR = 3;
  public int JJTNUMBER = 4;
  public int JJTISNUMBER = 5;


  public String[] jjtNodeName = {
    "start",
    "Add",
    "Mult",
    "Factor",
    "number",
    "ISnumber",
  };
}
/* JavaCC - OriginalChecksum=c7924aa0ae319d6127bb79d2cbdf019a (do not edit this line) */
