/* Generated By:JJTree&JavaCC: Do not edit this line. IdIndexerConstants.java */
package com.wanhive.basic.indexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IdIndexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTIGER_LITERAL = 2;
  /** RegularExpression Id. */
  int IDENTIFIER = 3;
  /** RegularExpression Id. */
  int SC = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<INTIGER_LITERAL>",
    "<IDENTIFIER>",
    "\";\"",
    "<DIGIT>",
  };

}
