/* Generated By:JavaCC: Do not edit this line. IdIndexerTreeConstants.java Version 5.0 */
package com.wanhive.basic.indexer;

public interface IdIndexerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCONSTANT = 1;


  public String[] jjtNodeName = {
    "Start",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=eced13e8b03c6ed8c458d9896302202d (do not edit this line) */
